config/routes.rb
Rails.application.routes.draw do
  resources :priority_lists
  resources :research_papers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "research_papers#index"

  match 'research_papers_update_priority', :to => 'research_papers#update_priority', :via => [:get, :post, :put]
  match 'priority_lists_create_blank', :to => 'priority_lists#create_blank', :via => [:get, :post, :put]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/priority_list.rb
class PriorityList < ApplicationRecord
end

app/models/research_paper.rb
class ResearchPaper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/priority_lists_controller.rb
class PriorityListsController < ApplicationController
  before_action :set_priority_list, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /priority_lists or /priority_lists.json
  def index
    @priority_lists = PriorityList.all
  end

  # GET /priority_lists/1 or /priority_lists/1.json
  def show
  end

  # GET /priority_lists/new
  def new
    @priority_list = PriorityList.new
  end

  # GET /priority_lists/1/edit
  def edit
  end

  # POST /priority_lists or /priority_lists.json
  def create
    @priority_list = PriorityList.new(priority_list_params)

    respond_to do |format|
      if @priority_list.save
        format.html { redirect_to priority_list_url(@priority_list), notice: "Priority list was successfully created." }
        format.json { render :show, status: :created, location: @priority_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @priority_list.errors, status: :unprocessable_entity }
      end
    end
  end

  #Create an empty priority list
  def create_blank
    newPriorityList = PriorityList.new
    newPriorityList.priority_list = ""
    newPriorityList.save
  end

  # PATCH/PUT /priority_lists/1 or /priority_lists/1.json
  def update
    respond_to do |format|
      if @priority_list.update(priority_list_params)
        format.html { redirect_to priority_list_url(@priority_list), notice: "Priority list was successfully updated." }
        format.json { render :show, status: :ok, location: @priority_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @priority_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /priority_lists/1 or /priority_lists/1.json
  def destroy
    @priority_list.destroy

    respond_to do |format|
      format.html { redirect_to priority_lists_url, notice: "Priority list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_priority_list
      @priority_list = PriorityList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def priority_list_params
      params.require(:priority_list).permit(:priority_list)
    end
end

app/controllers/research_papers_controller.rb
class ResearchPapersController < ApplicationController
  before_action :set_research_paper, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token
  # GET /research_papers or /research_papers.json
  def index
    @research_papers = ResearchPaper.all
    @currPriorityList = PriorityList.all.first
    @recentlyAddedPaper = ResearchPaper.all.last
    @firstResearchPaper = ResearchPaper.all.first
  end

  # GET /research_papers/1 or /research_papers/1.json
  def show
  end

  # GET /research_papers/new
  def new
    @research_paper = ResearchPaper.new
  end

  # GET /research_papers/1/edit
  def edit
  end

  # POST /research_papers or /research_papers.json
  def create
    @research_paper = ResearchPaper.new(research_paper_params)

    respond_to do |format|
      if @research_paper.save
        format.html { redirect_to research_paper_url(@research_paper), notice: "Research paper was successfully created." }
        format.json { render :show, status: :created, location: @research_paper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @research_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /research_papers/1 or /research_papers/1.json
  def update
    respond_to do |format|
      if @research_paper.update(research_paper_params)
        format.html { redirect_to research_paper_url(@research_paper), notice: "Research paper was successfully updated." }
        format.json { render :show, status: :ok, location: @research_paper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @research_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_priority
    #Get all the  parameters from ajax's url
    @newPriorityList = params[:priorityList]
    #Fetch the record from the database by term
    currPriorityList = PriorityList.first
    #Update the model and save
    currPriorityList.priority_list = @newPriorityList
    currPriorityList.save
  end

  # DELETE /research_papers/1 or /research_papers/1.json
  def destroy
    @research_paper.destroy

    respond_to do |format|
      format.html { redirect_to research_papers_url, notice: "Research paper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_research_paper
      @research_paper = ResearchPaper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def research_paper_params
      params.require(:research_paper).permit(:paper_name, :link, :authors, :style_or_type, :cross_references, :purpose, :dataset, :method,:results,:published_year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/priority_lists_helper.rb
module PriorityListsHelper
end

app/helpers/research_papers_helper.rb
module ResearchPapersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Research Paper Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "script" %>

    <!--Bootstrap 5.1.3-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/priority_lists/_form.html.erb
<%= form_with(model: priority_list) do |form| %>
  <% if priority_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(priority_list.errors.count, "error") %> prohibited this priority_list from being saved:</h2>

      <ul>
        <% priority_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :priority_list, style: "display: block" %>
    <%= form.text_field :priority_list %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/priority_lists/_priority_list.html.erb
<div id="<%= dom_id priority_list %>">
  <p>
    <strong>Priority list:</strong>
    <%= priority_list.priority_list %>
  </p>

</div>

app/views/priority_lists/edit.html.erb
<h1>Editing priority list</h1>

<%= render "form", priority_list: @priority_list %>

<br>

<div>
  <%= link_to "Show this priority list", @priority_list %> |
  <%= link_to "Back to priority lists", priority_lists_path %>
</div>

app/views/priority_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Priority lists</h1>

<div id="priority_lists">
  <% @priority_lists.each do |priority_list| %>
    <%= render priority_list %>
    <p>
      <%= link_to "Show this priority list", priority_list %>
    </p>
  <% end %>
</div>

<%= link_to "New priority list", new_priority_list_path %>

app/views/priority_lists/new.html.erb
<h1>New priority list</h1>

<%= render "form", priority_list: @priority_list %>

<br>

<div>
  <%= link_to "Back to priority lists", priority_lists_path %>
</div>

app/views/priority_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @priority_list %>

<div>
  <%= link_to "Edit this priority list", edit_priority_list_path(@priority_list) %> |
  <%= link_to "Back to priority lists", priority_lists_path %>

  <%= button_to "Destroy this priority list", @priority_list, method: :delete %>
</div>

app/views/research_papers/_form.html.erb
<%= form_with(model: research_paper) do |form| %>
  <% if research_paper.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(research_paper.errors.count, "error") %> prohibited this research_paper from being saved:</h2>

      <ul>
        <% research_paper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br>

  <fieldset>
    <legend>Basic Info</legend>
    <div class="form-inputs">
      <%= form.label :paper_name, style: "display: none" %>
      <%= form.text_field :paper_name, class: "form-control input-text", style:"width: 500px", placeholder: "Name of the Paper"  %>
    </div>

    <div class="form-inputs">
      <%= form.label :link, style: "display: none" %>
      <%= form.text_field :link, class: "form-control input-text", style:"width: 500px", placeholder: "Link to the paper" %>
    </div>

    <div class="form-inputs">
      <%= form.label :authors, style: "display: none" %>
      <%= form.text_field :authors, class: "form-control input-text", style:"width: 500px", placeholder: "Names of Authors (seperated with ~)" %>
    </div>

    <div class="form-inputs">
      <%= form.label :style_or_type, style: "display: none" %>
      <%= form.text_field :style_or_type, class: "form-control input-text", style:"width: 500px", placeholder: "Style/Type" %>
    </div>

    <div class="form-inputs">
      <%= form.label :cross_references, style: "display: none" %>
      <%= form.text_area :cross_references, class: "form-control input-text", style:"width: 500px; display:none;", placeholder: "Cross References (seperated with ~)" %>
    </div>

    <div class="form-inputs">
      <%= form.label :published_year, style: "display: none" %>
      <%= form.text_field :published_year, class: "form-control input-text", style:"width: 500px", placeholder: "Published Year" %>
    </div>
  </fieldset>

  <br>

  <fieldset>
    <legend>Summary</legend>
    <div class="form-inputs">
      <%= form.label :purpose, style: "display: none" %>
      <%= form.text_area :purpose, class: "form-control input-text", style:"width: 500px", placeholder: "Purpose" %>
    </div>

    <div class="form-inputs">
      <%= form.label :dataset, style: "display: none" %>
      <%= form.text_area :dataset, class: "form-control input-text", style:"width: 500px", placeholder: "Dataset" %>
    </div>

    <div class="form-inputs">
      <%= form.label :method, style: "display: none" %>
      <%= form.text_area :method, class: "form-control input-text", style:"width: 500px", placeholder: "Method" %>
    </div>

    <div class="form-inputs">
      <%= form.label :results, style: "display: none" %>
      <%= form.text_area :results, class: "form-control input-text", style:"width: 500px", placeholder: "Results" %>
    </div>
  </fieldset>

  <div class="form-inputs" style="width: fit-content; margin: auto;">
    <%= form.submit class: "btn btn-success", value: "Submit"%>
  </div>
<% end %>

app/views/research_papers/_research_paper.html.erb
<div id="<%= dom_id research_paper %>">

  <fieldset>
    <legend>Basic Info</legend>
  <p>
    <strong>Paper name:</strong>
    <%= research_paper.paper_name %>
  </p>

  <p>
    <strong>Style or type:</strong>
    <%= research_paper.style_or_type %>
  </p>

  <p>
    <strong>Authors:</strong>
    <%= research_paper.authors %>
  </p>

  <p>
    <strong>Link:</strong>
    <p style="word-wrap: break-word;"><%= research_paper.link %></p>
  </p>

  <p>
    <strong>Cross references:</strong>
    <%= research_paper.cross_references %>
  </p>

  <p>
    <strong>Published Year:</strong>
    <%= research_paper.published_year %>
  </p>

  </fieldset>

<br>

  <fieldset>
    <legend>Summary</legend>
  <p>
    <strong>Purpose:</strong>
    <%= research_paper.purpose %>
  </p>

  <p>
    <strong>Dataset:</strong>
    <%= research_paper.dataset %>
  </p>

  <p>
    <strong>Method:</strong>
    <%= research_paper.method %>
  </p>

  <p>
    <strong>Results:</strong>
    <%= research_paper.results %>
  </p>
</fieldset>
</div>

app/views/research_papers/edit.html.erb
<div class = "mycard center-in-screen" style="padding:20px; width: fit-content;">
  
  <h1 id="main-heading">Edit</h1>

  <%= render "form", research_paper: @research_paper %>

  <br>

    <div>
      <%# <%= link_to "Show this research paper", @research_paper, class: "btn btn-secondary" %> 
      <%= link_to "Back", research_papers_path, class: "btn btn-dark" %>
    </div>

</div>

app/views/research_papers/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">



<h1 id="main-heading">Research Paper Tracker</h1>




<div id="research_papers" class="mycard center-in-screen">
  <div style="height: auto; width:fit-content; margin: auto;">
    <%= link_to "Add a Paper", new_research_paper_path, :class => "btn btn-success button-control new-button " %>
  </div>
  <div id="sortableList">
  </div>
</div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.10.2/Sortable.min.js"></script>
  <!-- Import JQuery -->
  <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>





  <script>

    //Global Variables
    var currentPriorityList;
    var allResearchPapers = [];


    //Check if we have a priority_list
    <% if @currPriorityList == nil %>
      createPriorityList();
    <% else %>
      currentPriorityList = '<%=@currPriorityList.priority_list%>';
      console.log("Current Priority List:");
      console.log(currentPriorityList);
      currentPriorityList = currentPriorityList.split('~');
    <% end %>

    //Remove empty element from priority list
    if(currentPriorityList[0]==""){
      currentPriorityList.splice(0,1);
    }


    //If we have papers, check if we've added them to the priority list
    <%  if @firstResearchPaper != nil and @recentlyAddedPaper != nil%>
      checkForPendingPapers();
    <% end %>






  populateResearchPaperObjects();


  displayPrioritisedList(currentPriorityList);

  var dragArea = document.querySelector("#sortableList");
  var sortableList = new Sortable(dragArea, {
      animation: 250,

      onUpdate: function(ev) {

          var prioritisedList = sortableList.toArray();
          //Update Priority List with new Sorting
          console.log("Sorting Changed");
          console.log(prioritisedList);
          var priorityListString = createPriorityListString(prioritisedList);

          console.log("Priority List String: ");
          console.log(priorityListString);

          updatePriorityList(priorityListString);

      },

  });


  function populateResearchPaperObjects(){
    <% @research_papers.each do |research_paper| %>
      var researchPaper = new ResearchPaperItem('<%=research_paper.id%>','<%=research_paper.paper_name%>');
       researchPaper.populateAuthorArray('<%=research_paper.authors%>');
       researchPaper.setLink('<%=research_paper.link%>');
       researchPaper.setStyle('<%=research_paper.style_or_type%>');
       researchPaper.setPurpose('<%=research_paper.purpose%>');
       researchPaper.setMethod('<%=research_paper.method%>');
       researchPaper.setDataset('<%=research_paper.dataset%>');
       researchPaper.setResults('<%=research_paper.results%>');
       researchPaper.setPublishedYear('<%=research_paper.published_year%>');
       console.log("Published year is: " + '<%=research_paper.published_year%>');

      allResearchPapers.push(researchPaper);
    <% end %>
  }

  function checkForPendingPapers(){
       //Check if we have a pending paper to add to the Priority List
       var counter = 0;

       <% @research_papers.each do |research_paper| %>
        counter = counter+1;
        console.log("Found a paper");
       <% end %>
       console.log(counter);
       console.log(currentPriorityList.length);
       console.log(currentPriorityList);
       if(counter !=0){
         //If we have an extra paper that isn't counted in our priority list
         if(counter-1 == currentPriorityList.length){
           console.log("We have a pending paper");
           <% if @recentlyAddedPaper != nil%>
            addToPriorityList('<%=@recentlyAddedPaper.id%>');
           <% end %>
           updatePriorityList(createPriorityListString(currentPriorityList));
           //window.location.reload();
         }
       }
     }
</script>

</div>

app/views/research_papers/new.html.erb
<div class = "mycard center-in-screen" style="padding:20px; width: fit-content;">

<h1 id="main-heading">New Paper</h1>

<%= render "form", research_paper: @research_paper %>

<br>

<div>
  <%= link_to "Back", research_papers_path, class: "btn btn-dark" %>
</div>

</div>

app/views/research_papers/show.html.erb
<p style="color: green"><%= notice %></p>
<div class = "mycard center-in-screen form-card" style="padding:20px; width: fit-content;">

  <h1 id="main-heading">Details</h1>
<br>
<%= render @research_paper %>

<br>
  <div style="display:flex; flex-direction:row;">
    <%= link_to "Back to research papers", research_papers_path, class: "btn btn-dark button-control" %>
    <%= link_to "Edit this research paper", edit_research_paper_path(@research_paper), class: "btn btn-success button-control" %>
    <%= button_to "Destroy this research paper", @research_paper, method: :delete, data: { confirm: 'Are you sure you want to remove this paper?' }, class: "btn btn-danger button-control", style:"display:none;" %>

  </div>

</div>